### ISSUE TITLE
Minecraft Spigot Template Overwrites config file

### ISSUE THREAD

**Issue by maxfire2008** [PufferPanel/templates#113]
The minecraft spigot template (`/minecraft-spigot/minecraft-spigot.json`) overwrites settings in `server.properties` when installing including the whitelist config variable! So after manually being edited the config file is reset to have potentially insecure options in it.

**Comment by Zoey2936** [comment]
Yes, this is a problem from the pufferpanel, every template which edits configuration resets them to only the values which are set

**Comment by maxfire2008** [comment]
I seem to remember there is a way to replace values in a file with a regex?
