### ISSUE TITLE
ARK: Survival Evolved – TotalConversionMod

### ISSUE THREAD

**Issue by LiaraAlis** [PufferPanel/templates#21]
Currently, it is not possible to add Primitive Plus DLC (for example) to the ARK server.
My suggestion is to introduce the "TotalConversionMod" argument as configurable variable in the template.

**Comment by LordRalex** [comment]
Is the TCM an actual mod or is it just DLC that they call a mod with the name?

**Comment by LiaraAlis** [comment]
Total Conversion Modifications are mods that, unlike normal mods, change the entire gameplay.
Primitive Plus is a official DLC and must be enabled with the `TotalConversionMod` argument in the start command.

**Comment by LordRalex** [comment]
Is there a reason to *not* enable this? What I'm wondering is if we should just always add it.

**Comment by LiaraAlis** [comment]
Yes, there is a reason:
As I said, the mod completely changes the entire gameplay, for example there are significantly more construction possibilities.
It could be that you want to stay in the standard. In addition, there are more total conversion mods or official TCM DLCs that do this, so it would make sense to be able to configure it.

If you want, I can do this changes and make a pull request if I have some time for this. So I can try the effect to the server to ensure all is working fine. So I could possibly also make sure that one can activate further Mods.
Maybe it is also possible to load mods and the total conversion mod via the ini file, I'm not deep enough in the subject yet.
But I have to try it all first.

**Comment by LordRalex** [comment]
If you want to do a PR, you are welcome to. I don't play Ark so I have no idea what their settings do.

**Comment by LiaraAlis** [comment]
After my tests I noticed that it seems to be sufficient to set this via `GameUserSettings.ini`, therefore a parameter is not required.
I therefore close this issue.
