### ISSUE TITLE
7 days to die, cannot install

### ISSUE THREAD

**Issue by cronner** [PufferPanel/templates#223]
Starting process: /var/lib/pufferpanel/binaries/dotnet-runtime/dotnet /var/lib/pufferpanel/binaries/depotdownloader/DepotDownloader.dll -app 294420 -dir /var/lib/pufferpanel/servers/50b441ef
=No username given. Using anonymous account with dedicated server subscription.
Connecting to Steam3... Done!
Logging anonymously into Steam3... Done!
Using Steam3 suggested CellID: 41
Got AppInfo for 294420
Using app branch: 'Public'.
Warning: Depot 294422 does not have branch named "Public". Trying public branch.
Depot 294422 () missing public subsection or manifest section.
Total downloaded: 0 bytes (0 bytes uncompressed) from 0 depots
Disconnected from Steam
DAEMON
 Executing: chmod +x 7DaysToDieServer.x86_64
DAEMON
 Starting process: /usr/bin/chmod +x 7DaysToDieServer.x86_64
chmod: cannot access '7DaysToDieServer.x86_64': No such file or directory
DAEMON
 Server installed

**Comment by LordRalex** [comment]
You'll need to download a dev version of DepotDownloader (DepotDownloader-Windows-framework.zip from https://github.com/SteamRE/DepotDownloader/actions/runs/5153489983) and place the extracted files into /var/lib/pufferpanel/binaries/depotdownloader/
