### ISSUE TITLE
ARK: Survival Evolved – Merging "ark" and "arkprivate"

### ISSUE THREAD

**Issue by LiaraAlis** [PufferPanel/templates#23]
I suggest to merge both templates and make it possible to configure more startup parameters. So parameters like `-exclusivejoin` can be added variably and it doesn't need two different templates.
In addition, it opens other possibilities for the server admin, which were blocked before.

**Comment by LordRalex** [comment]
Closed as now single template with the changes needed

**Comment by LiaraAlis** [comment]
Thanks for this, but wouldn't it be better to simply call the template directory "ark"? :D

**Comment by LordRalex** [comment]
Yes, but editing folder names is harder through Github directly, and I was too lazy to do it on my machine.
