### ISSUE TITLE
Satisfactory template can't find the gamefiles on Steam

### ISSUE THREAD

**Issue by ExotiscHD** [PufferPanel/templates#254]
![grafik](https://github.com/pufferpanel/templates/assets/156721119/3d80ef47-1970-4546-befa-207fe74aee3d)
It is also not possible to change the game branch to experimental.
If you change the game branch to "experimental", through the drop down menu when setting up the server, it still tries to download the public branch.

**Comment by LordRalex** [comment]
Update your panel

**Comment by ExotiscHD** [comment]
Thank you
