### ISSUE TITLE
Rust Template Broken

### ISSUE THREAD

**Issue by TheDeadCPU** [PufferPanel/templates#27]
The rust template seems to be broken.

Once starting the server after install you get this:

> Waiting for user info...OK
> Success! App '258550' already up to date.
> runds.sh: 1: export:
> : bad variable name
> Running post-execution steps

And the server never starts.

Content of runds.sh is the following:

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/RustDedicated_Data/Plugins/x86_64 
> ./RustDedicated "$@"

**Comment by TheDeadCPU** [comment]
I see that someone mentioned this on the forum in august. 
[https://community.pufferpanel.com/topic/726/rust-template/4](url)

**Comment by TheDeadCPU** [comment]
I have tried changing the top line of runds.sh to:

> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/RustDedicated_Data/Plugins$

This makes the server at least try to start, but it'll fail and throw this:

> Starting server
> Executing: steamcmd/steamcmd.sh +login anonymous +force_install_dir /var/lib/pufferd/servers/f751ebc3-07d2-4a33-8803-94212f741170 +app_update 258550 +quit
> Redirecting stderr to '/var/lib/pufferd/servers/f751ebc3-07d2-4a33-8803-94212f741170/Steam/logs/stderr.txt'
> [  0%] Checking for available updates...
> [----] Verifying installation...
> Steam Console Client (c) Valve Corporation
> -- type 'quit' to exit --
> Loading Steam API...OK.
> 
> Connecting anonymously to Steam Public...Logged in OK
> Waiting for user info...OK
> Success! App '258550' already up to date.
> Set current directory to /var/lib/pufferd/servers/f751ebc3-07d2-4a33-8803-94212f741170
> Found path: /var/lib/pufferd/servers/f751ebc3-07d2-4a33-8803-94212f741170/RustDedicated
> Mono path[0] = '/var/lib/pufferd/servers/f751ebc3-07d2-4a33-8803-94212f741170/RustDedicated_Data/Managed'
> Mono config path = '/var/lib/pufferd/servers/f751ebc3-07d2-4a33-8803-94212f741170/RustDedicated_Data/MonoBleedingEdge/etc'
> Preloaded 'libRakNet.so'
> Preloaded 'libRustNative.so'
> eac_server.so [x64] :: OnLoad()
> Preloaded 'libeac_server.so'
> Preloaded 'libeasyanticheat.so'
> Preloaded 'libsteam_api64.so'
> Preloaded 'steamclient.so'
> Unable to preload the following plugins:
> 	libRenderer.so
> 	libRustNative.so
> 	libRenderer.so
> 	sqlite3.so
> Initialize engine version: 2018.3.3f1 (393bae82dbb8)
> Forcing GfxDevice: Null
> GfxDevice: creating device client; threaded=0
> NullGfxDevice:
>     Version:  NULL 1.0 [1.0]
>     Renderer: Null Device
>     Vendor:   Unity Technologies
> Command Line: "./RustDedicated" "-nographics" "-batchmode" "+server.port" "27015" "+server.level" ""Procedural Map"" "+server.seed" "389272" "+server.worldsize" "3000" "+server.maxplayers" "10" "+server.hostname" ""Vodka Rust"" "+server.description" ""Vodka Rust"" "+server.headerimage" ""http://"" "+server.url" ""http://"" "+server.identity" ""server1"" "+rcon.port" "28016" "+rcon.password" "******" "+rcon.web 1" "-logfile 2>&1" 
> Command 'nographics' not found
> Command 'batchmode' not found
> server.port: "27015"
> server.level: "Procedural"
> server.seed: "389272"
> server.worldsize: "3000"
> server.maxplayers: "10"
> server.hostname: "_redacted_"
> server.description: "_redacted_"
> server.headerimage: "http://"
> server.url: "http://"
> server.identity: "server1"
> rcon.port: "28016"
> Command 'rcon.password' not found
> rcon.web: "True"
> Command 'logfile 2>&1' not found
> [Manifest] URI IS "https://api.facepunch.com/api/public/manifest/?public_key=j0VF6sNnzn9rwt9qTZtI02zTYK8PRdN1"
>  
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> Command 'nographics' not found
> Command 'batchmode' not found
> server.port: "27015"
> server.level: "Procedural"
> server.seed: "389272"
> server.worldsize: "3000"
> server.maxplayers: "10"
> server.hostname: "_redacted_"
> server.description: "_redacted_"
> server.headerimage: "http://"
> server.url: "http://"
> server.identity: "server1"
> rcon.port: "28016"
> Command 'rcon.password' not found
> rcon.web: "True"
> Command 'logfile 2>&1' not found
> Server Config Loaded
> WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
> WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
> Asset Warmup (245/5291)
> Asset Warmup (822/5291)
> Asset Warmup (2530/5291)
> Asset Warmup (2973/5291)
> Asset Warmup (3102/5291)
> Asset Warmup (3776/5291)
> Asset Warmup (3949/5291)
> Asset Warmup (4470/5291)
> Asset Warmup (5291/5291)
> WebSocket RCon Started on 28016
>  
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> Map Spawned 0 entities
> Couldn't load server/server1/bootstrap.3000.389272.175.sav - file doesn't exist
>  
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> Missing EnvSync - creating
>  
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> Missing CommunityEntity - creating
>  
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> Missing ResourceDepositManager - creating
>  
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> Missing RelationshipManager - creating
>  
> (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
> 
> Setting breakpad minidump AppID = 252490
> 192.168.1.10:58581/76561197992769369/Vodka🍸 disconnecting: NullReferenceException: Object reference not set to an instance of an object
> UIBlueprints.UpdateBlueprints (System.Collections.Generic.IEnumerable`1[T] list) (at <1e0951a9483643df9007830ed9549978>:0)
> UIBlueprints.UpdateBlueprintList () (at <1e0951a9483643df9007830ed9549978>:0)
> UIBlueprints.Refresh () (at <1e0951a9483643df9007830ed9549978>:0)
> PlayerBlueprints.ClientInit () (at <1e0951a9483643df9007830ed9549978>:0)
> BasePlayer.InitLocalPlayer () (at <1e0951a9483643df9007830ed9549978>:0)
> BasePlayer.ClientInit (ProtoBuf.Entity info) (at <1e0951a9483643df9007830ed9549978>:0)
> BaseNetworkable.ClientSpawn (ProtoBuf.Entity info) (at <1e0951a9483643df9007830ed9549978>:0)
> Client.CreateOrUpdateEntity (ProtoBuf.Entity info, System.Int64 size) (at <1e0951a9483643df9007830ed9549978>:0)
> Client.OnEntities (Network.Message packet) (at <1e0951a9483643df9007830ed9549978>:0)
> Client.OnNetworkMessage (Network.Message packet) (at <1e0951a9483643df9007830ed9549978>:0)
> Facepunch.Network.Raknet.Client.HandleMessage () (at <436c910400a14247ad723acaafc71c3e>:0)
> UnityEngine.Debug:LogException(Exception)
> Facepunch.Network.Raknet.Client:HandleMessage()
> Facepunch.Network.Raknet.Client:Cycle()
> Client:Update()
> 
> Version: 32268

**Comment by TheDeadCPU** [comment]
Seems like adding $ to the end of the first line fixes the issue.

So changing the runds.sh file to:
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/RustDedicated_Data/Plugins/x86_64
>./RustDedicated "$@"
Solves the issue.

But then I run into a new issue when trying to join the server.
![image](https://user-images.githubusercontent.com/529537/53114186-8ca1b680-3543-11e9-9086-0844ee4d43aa.png)

**Comment by LordRalex** [comment]
I don't play Rust, so I can't really help determine that specific issue. 

I think though that I exposed a way to set environment variables so that the crazy script wasn't needed, I'll have to look at it though.

**Comment by LordRalex** [comment]
Are you able to test the following JSON and see if it works?

```json
{
	"pufferd": {
		"type": "srcds",
		"display": "Rust Public Server",
		"install": {
			"commands": [
				{
					"files": "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz",
					"type": "download"
				},
				{
					"target": "steamcmd",
					"type": "mkdir"
				},
				{
					"commands": [
						"tar --no-same-owner -xzvf steamcmd_linux.tar.gz -C steamcmd",
						"steamcmd/steamcmd.sh +login anonymous +force_install_dir ${rootdir} +app_update 258550 +quit"
					],
					"type": "command"
				}
			]
		},
		"run": {
			"stopCode": 2,
			"pre": [
				{
					"commands": [
						"steamcmd/steamcmd.sh +login anonymous +force_install_dir ${rootdir} +app_update 258550 +quit"
					],
					"type": "command"
				}
			],
			"post": [],
			"arguments": [
				"-nographics",
				"-batchmode",
				"+server.port",
				"${port}",
				"+server.level",
				"\"${ServerLevel}\"",
				"+server.seed",
				"${ServerSeed}",
				"+server.worldsize",
				"${WorldSize}",
				"+server.maxplayers",
				"${MaxPlayers}",
				"+server.hostname",
				"\"${ServerName}\"",
				"+server.description",
				"\"${Description}\"",
				"+server.headerimage",
				"\"${ServerImage}\"",
				"+server.url",
				"\"${URL}\"",
				"+server.identity",
				"\"${ServerIdentity}\"",
				"+rcon.port",
				"${RConPort}",
				"+rcon.password",
				"${RConPassword}",
				"+rcon.web 1",
				"-logfile 2>&1"
			],
			"program": "./RustDedicated",
			"environmentVars": {
				"LD_LIBRARY_PATH": "$LD_LIBRARY_PATH:${rootdir}/RustDedicated_Data/Plugins/x86_64"
			}
		},
		"environment": {
			"type": "tty"
		},
		"data": {
			"ip": {
				"value": "0.0.0.0",
				"required": true,
				"desc": "What IP to bind the server to",
				"display": "IP",
				"internal": false
			},
			"port": {
				"value": "27015",
				"required": true,
				"desc": "What port to bind the server to",
				"display": "Port",
				"internal": false,
				"type": "integer"
			},
			"ServerLevel": {
				"value": "Procedural Map",
				"required": true,
				"desc": "What map name do you want? If unsure, leave as default.",
				"display": "Server Level",
				"internal": false
			},
			"ServerSeed": {
				"value": "1234",
				"required": true,
				"desc": "Server seed to use. Default should be fine.",
				"display": "Server Seed",
				"internal": false
			},
			"WorldSize": {
				"value": "3000",
				"required": true,
				"desc": "World size (number)",
				"display": "World Size",
				"internal": false
			},
			"MaxPlayers": {
				"value": "10",
				"required": true,
				"desc": "Maximum number of players to support",
				"display": "Max Players",
				"internal": false
			},
			"ServerName": {
				"value": "RUST Public Server",
				"required": true,
				"desc": "Name of the server to use",
				"display": "Server Name",
				"internal": false
			},
			"Description": {
				"value": "RUST Public Server Description",
				"required": true,
				"desc": "Server description shown on server browser",
				"display": "Server Description",
				"internal": false
			},
			"ServerImage": {
				"value": "http://",
				"required": true,
				"desc": "URL For the server image banner",
				"display": "Server Header Image",
				"internal": false
			},
			"URL": {
				"value": "http://",
				"required": true,
				"desc": "URL for the website dedicated to this server.",
				"display": "Server Website",
				"internal": false
			},
			"ServerIdentity": {
				"value": "server1",
				"required": true,
				"desc": "Server identity to use, leave as default unless you know what you're doing",
				"display": "Server identity",
				"internal": false
			},
			"RConPort": {
				"value": "28016",
				"required": true,
				"desc": "Port to use for RCON",
				"display": "RCON Port",
				"internal": false
			},
			"RConPassword": {
				"value": "letmein",
				"required": true,
				"desc": "Password to use on RCON. CHANGE THIS",
				"display": "RCON Password",
				"internal": false
			}
		}
	}
}
```

**Comment by TheDeadCPU** [comment]
This json completely crashes pufferd. 
This is the log from /var/log/pufferd

```
[15:49:55] [INFO] pufferd 1.2.6 (e1db6eafa968018b955db659ac4ed1e943c75fda)
[15:49:55] [INFO] Logging set to INFO
[15:49:55] [INFO] Loaded server 11c831f4-55e3-4c06-a7f1-954aa226294a
[15:49:55] [INFO] Loaded server 9cd229eb-1ebf-4dee-baf1-9516317bc344
[15:49:55] [INFO] Loaded server dfdf6ff4-b2f5-489f-8743-3bc03e541bbd
[15:49:55] [WARN] No HTTPS.PEM found in data folder, will use http instead
[15:49:55] [DEBUG] Loading existing key
[15:49:55] [INFO] Started SFTP Server on 0.0.0.0:5657
[15:49:55] [INFO] Starting web access on 0.0.0.0:5656
[15:50:12] [DEBUG] Destroying server 9cd229eb-1ebf-4dee-baf1-9516317bc344
[15:50:24] [DEBUG] Creating server 15162248-70e0-4a59-b66a-140b6ba8d739
[15:50:48] [DEBUG] Installing server 15162248-70e0-4a59-b66a-140b6ba8d739
[15:50:48] [DEBUG] Server 15162248-70e0-4a59-b66a-140b6ba8d739 has defined install data
[15:50:48] [DEBUG] Download file from https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz to /var/lib/pufferd/servers/15162248-70e0-4a59-b66a-140$
[15:50:49] [DEBUG] Making directory: steamcmd

[15:50:49] [DEBUG] Executing command: tar --no-same-owner -xzvf steamcmd_linux.tar.gz -C steamcmd

```
This is the output from journalctl 
```
Feb 26 15:49:55 redactedgame systemd[1]: Started pufferd daemon service.
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [INFO] No config passed, defaulting to /etc/pufferd/config.json
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [INFO] pufferd 1.2.6 (e1db6eafa968018b955db659ac4ed1e943c75fda)
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [INFO] Logging set to INFO
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [INFO] Loaded server 11c831f4-55e3-4c06-a7f1-954aa226294a
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [INFO] Loaded server 9cd229eb-1ebf-4dee-baf1-9516317bc344
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [INFO] Loaded server dfdf6ff4-b2f5-489f-8743-3bc03e541bbd
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [WARN] No HTTPS.PEM found in data folder, will use http instead
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [INFO] Started SFTP Server on 0.0.0.0:5657
Feb 26 15:49:55 redactedgame pufferd[1559]: [15:49:55] [INFO] Starting web access on 0.0.0.0:5656
Feb 26 15:50:49 redactedgame pufferd[1559]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 26 15:50:49 redactedgame systemd[1]: pufferd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 26 15:50:49 redactedgame systemd[1]: pufferd.service: Control process exited, code=exited status=2
Feb 26 15:50:49 redactedgame systemd[1]: pufferd.service: Unit entered failed state.
Feb 26 15:50:49 redactedgame systemd[1]: pufferd.service: Failed with result 'exit-code'.

```

**Comment by LordRalex** [comment]
I'll have to play with it some more then. It should have logged the stack from where it failed at though, so a bit concerned why it didn't log that. 

It acts like the tar command just fully fubar'ed itself.

**Comment by TheDeadCPU** [comment]
Yeah that's kinda weird because it's the same exact command and stuff as the original config, and I tested that one just to make sure.
(I've tested this back and forth between the two jsons 3-4 times just to make sure it wasn't a fluke)

**Comment by LordRalex** [comment]
And the new one consistently fails at the same point?

**Comment by TheDeadCPU** [comment]
Yup, it fails at the same exact point every time.

**Comment by rootathome** [comment]
Hi, look at this:
https://github.com/rootathome/PufferPanel-templates
its work for me.
