### ISSUE TITLE
${rootdir} variable in template not interpreted (i.e. ark)

### ISSUE THREAD

**Issue by tiramon** [PufferPanel/templates#47]
Tried with Pufferpanel v2.0
the ark template tells steamcmd to install the server in ${rootdir} ... and steam takes this a bit to literal

/var/lib/pufferpanel/servers/77c7f398/steamcmd/${rootdir} # ls -l
total 31972
drwxr-xr-x 7 pufferpanel pufferpanel     4096 Aug 10 09:09 Engine
drwxr-xr-x 2 pufferpanel pufferpanel     4096 Aug 10 09:09 linux64
-rwxr-xr-x 1 pufferpanel pufferpanel  4464277 Aug 10 09:05 PackageInfo.bin
drwxr-xr-x 5 pufferpanel pufferpanel     4096 Aug 10 09:09 ShooterGame
drwxr-xr-x 5 pufferpanel pufferpanel     4096 Aug 10 09:09 steamapps
-rwxr-xr-x 1 pufferpanel pufferpanel 28246246 Aug 10 09:05 steamclient.so
-rwxr-xr-x 1 pufferpanel pufferpanel      272 Aug 10 09:07 SteamCMDInstall.sh
-rwxr-xr-x 1 pufferpanel pufferpanel        9 Aug 10 09:07 version.txt

This also resolves in an error afterward because the server files are not where pufferpanel expects them to be

**Comment by LordRalex** [comment]
Resolved via https://github.com/PufferPanel/templates/commit/677f5f181aab75ef15ccfc7ca1c56981e3f95f62
