### ISSUE TITLE
Updating Minecraft

### ISSUE THREAD

**Issue by kasperhartwich** [PufferPanel/templates#80]
Hi. What is the process for updating Minecraft Bedrock to a new version? Right now the zip command prompts for overwriting the existing files if I select to run the install script, but are unsure if this is the right way to do it?

**Comment by nepcore** [comment]
I don't know much about Bedrock, but for the Java version just hitting install is the way to do so as it doesn't touch the world files

If that's different for Bedrock and it ends up killing data, then that's of course not as much of a viable option, however, all you can currently do about that without needing changes to PufferPanel would be to download the important files, run the install and then reupload the important files that were overwritten by the install routine

**Comment by kasperhartwich** [comment]
I don't think the downloading and unpacking overwrites the game, but right now it does not work as it prompts for overwriting the existing gamefiles.

**Comment by kasperhartwich** [comment]
I believe this will fix it.
